# MySQL config described here:
# https://springframework.guru/configuring-spring-boot-for-mysql
spring.h2.console.enabled: true

# NOTE: If this was actually a production database, you not tell Hibernate
# to use the create-drop option. This tells Hibernate to recreate the database on startup.
# Definitely not the behavior we want.
# You can set this property to the following values:
# none, validate, update, create-drop.
# If this was actually a production database, you probably would want to use validate.

spring.datasource.url: jdbc:mysql://localhost:3306/neukralin
spring.datasource.username: shoomarsi
spring.datasource.password: vramubo99_+ra/
spring.jpa.hibernate.ddl-auto: update

#spring.jpa.hibernate.ddl-auto: update

spring.http.multipart.max-file-size: 50MB
spring.http.multipart.max-request-size: 50MB

management.security.enabled: true
management.context-path: /admin/

spring.jpa.properties.hibernate.generate_statistics: false
spring.jpa.show-sql: false


app.admin.username: "Zala"
app.admin.password: "frobukaram753&)la+2"

cgu-url: "https://www.dailymotion.com/embed/video/k12tO5H7YXMWlTnNXly"
display-url: "https://www.dailymotion.com/embed/video/k6yTqZLiEei3cPrRynl"

spring:
  mail:
    host: mailhost.rd.francetelecom.fr
    port: 2525

server:
  port: 12345
